### PR TITLE
Upmerge latest commits from the CKEditor4 original repository

### PR DESCRIPTION
**Pull request by deti**
To be able to resolve https://trello.com/c/ZcjT5dLq/589-unc-nash-editing-lists-switches-the-order-of-list-items-with-no-warning

We need to cherry-pick this fix https://github.com/ckeditor/ckeditor4/commit/3343223a with surrounding tests. However, we couldn't do it without this huge up merge from the original repository.

It should be safe to sync `major` branch, because our main branch is `pstat`.

### CODE REVIEW

**Comment by stefanbrand-rldatix** [comment]
Is the fix that we need not in the `stable` branch release yet? I think the `major` branch is considered to be beta, which may have other issues

**Comment by deti** [comment]
@sbrand83 Correct. Overlooked it at all 🤦‍♂ 

The fix in all these branches:
```
origin/master
origin/latest
origin/major
origin/stable
```

https://github.com/ckeditor/ckeditor4#available-branches
```
master – Development of the upcoming minor release.
major – Development of the upcoming major release.
stable – Latest stable release tag point (non-beta).
latest – Latest release tag point (including betas).
release/A.B.x (e.g. 4.0.x, 4.1.x) – Release freeze, tests and tagging. Hotfixing.
```

Which one is better to merge?

**Comment by stefanbrand-rldatix** [comment]
If I had to pick one it would be the stable branch, but if you want to just cherry pick a single commit I guess it doesn't really matter which branch it comes from. Using this branch for that seems fine on second thought

**Comment by deti** [comment]
@sbrand83 Yes. I'm going to cherry-pick the fix for this issue only.

**Review by stefanbrand-rldatix — APPROVED** [review]
since we are only looking to cherrypick the one commit and this is not the branch we build our version of the editor on this should be fine to merge

**Pull request merged**
